const REGEX = {
  DIGIT_REGEX: /^\d+$/,
  ALPHANUMERIC_REGEX: /^[a-z0-9]+$/,
};

const KEYBOARD_KEYCODE = {
  BACKSPACE_KEYCODE: 8,
  ARROW_LEFT_KEYCODE: 37,
  ARROW_UP_KEYCODE: 38,
  ARROW_RIGHT_KEYCODE: 39,
  ARROW_DOWN_KEYCODE: 40,
  DELETE_KEYCODE: 46,
  SPACE_KEYCODE: 32,
}

const KEYBOARD_CODE = {
  BACKSPACE_CODE: 'Backspace',
  ARROW_LEFT_CODE: 'ArrowLeft',
  ARROW_UP_CODE: 'ArrowUp',
  ARROW_RIGHT_CODE: 'ArrowRight',
  ARROW_DOWN_CODE: 'ArrowDown',
  DELETE_CODE: 'Delete',
  SPACE_CODE: 'Space',
}

export {
  REGEX,
  KEYBOARD_KEYCODE,
  KEYBOARD_CODE
}
